### ISSUE TITLE
No ready pod for deployment `grafana` in ns `istio-system` when using kfctl_openshift_tekton_kfserving.v1.10.yaml

### ISSUE THREAD

**Issue by shawnzhu** [IBM/KubeflowDojo#83]
After deploying `kfctl_openshift_tekton_kfserving.v1.10.yaml` successfully, I found no pod for deployment `grafana`.

When running `oc get deploy -n istio-system -o yaml grafana`, it will show messages like:

```YAML
   message: 'pods "grafana-68bcfd88b6-" is forbidden: unable to validate against
      any security context constraint: [fsGroup: Invalid value: []int64{472}: 472
      is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser:
      Invalid value: 472: must be in the ranges: [1000930000, 1000939999]]'
    reason: FailedCreate
```

I noticed that it doesn't specify any service account nor SCC for it. so guess it needs to add it to allow fsGroup id `472`
